application: saveclothes
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/(.*\.(html|css|js|gif|jpg|png|ico|swf|ogg|mp3|eot|woff))
  static_files: static/\1
  upload: static/.*
  expiration: "0"

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest